# Generated by Django 2.1.1 on 2018-10-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(default='123456', max_length=30)),
                ('phone_number', models.IntegerField(null=True)),
                ('create_time', models.DateTimeField()),
            ],
        ),
    ]
