# Generated by Django 2.1.1 on 2018-09-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(max_length=10)),
                ('money', models.FloatField()),
                ('project_principle', models.CharField(max_length=20, unique=True)),
                ('project_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('taxpayer_id', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('bank', models.CharField(max_length=100)),
                ('bank_user', models.IntegerField()),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
    ]
