# Generated by Django 2.1.1 on 2018-10-11 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20181010_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_received', models.FloatField()),
                ('money_receivable', models.FloatField()),
                ('pay_type', models.CharField(max_length=5)),
                ('remark', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(null=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice')),
            ],
        ),
    ]
