# Generated by Django 2.1.1 on 2018-10-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_accountlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
