# Generated by Django 2.1.1 on 2018-10-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoice_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountlist',
            name='money_receivable',
        ),
    ]
