# Generated by Django 2.1.1 on 2018-10-12 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_remove_accountlist_money_receivable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_principle', models.CharField(max_length=20)),
                ('project_name', models.CharField(max_length=100)),
                ('money', models.FloatField()),
                ('remark', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(null=True)),
                ('state', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.User')),
            ],
        ),
    ]
