# Generated by Django 2.1.1 on 2018-10-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_expend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expend',
            old_name='money',
            new_name='expend_money',
        ),
        migrations.AddField(
            model_name='expend',
            name='expend_content',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
