# Generated by Django 2.1.1 on 2018-10-24 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_auto_20181018_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountlist',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='expend',
            name='user',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.DeleteModel(
            name='AccountList',
        ),
        migrations.DeleteModel(
            name='Expend',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
